name: fireball_calculator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=2.0.0
  - matplotlib>=3.9.0
  - pandas>=2.3.0
  - pillow>=11.0.0
  - scipy>=1.13.0
  - pip:
    - PySide6>=6.9.0
    - opencv-python>=4.11.0